### PR TITLE
quiet data provenance logs

### PR DESCRIPTION
**Pull request by ewollesen**
Warnings about missing user id fields were being logged in cases where we don't expect there to be a user id. Namely, when the request is using a server session token.

Waiting for #723 before merging.

### CODE REVIEW

**Comment by ewollesen** [comment]
Assuming this is approved as is, would you have any objection to this be merged without QA as a "trivial change" as per our process docs?

**Review by darinkrauss — DISMISSED** [review]
This looks fine. At some point we might want to clean up the entire provenance code block and separate it into a two separate paths based upon whether `IsService()` is true or not since we appear to want to capture different things in each case.

Bypassing QA would be up to Todd.

**Review by darinkrauss — APPROVED** [review]

**Comment by ewollesen** [comment]
@toddkazakov does this count as a "trivial" change for you?

**Comment by toddkazakov** [comment]
@ewollesen I think this is a question for @tjotala

**Review by tjotala — APPROVED** [review]
LGTM 🚢 

OK to bypass QA

**Pull request merged**
