### PR TITLE
Retire the use of groupId in favour of sharerId

### PR DESCRIPTION
**Pull request by toddkazakov**
This fixes a bug, which might leave user's account in an inconsistent state if a user with whom an account was shared is deleted.

### CODE REVIEW

**Review by derrickburns — DISMISSED** [review]
Lgtm

**Review by pazaan — APPROVED** [review]
LGTM :shipit:

**Review by derrickburns — APPROVED** [review]
LGTM

**Comment by tjotala** [comment]
@derrickburns @pazaan looks like @toddkazakov is requesting re-review?

**Comment by toddkazakov** [comment]
@tjotala I rebased the PR

**Review by derrickburns — APPROVED** [review]
Lgtm

**Review by tjotala — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
