### PR TITLE
Revert changes in develop that are not in master.

### PR DESCRIPTION
**Pull request by toddkazakov**
This PR will revert all changes in `develop` that are not in `master`. 

```
todd@todd-VirtualBox:~/go/src/github.com/tidepool-org/platform$ git checkout -b revert-develop
Switched to a new branch 'revert-develop'
todd@todd-VirtualBox:~/go/src/github.com/tidepool-org/platform$ git commit-tree 9d84997^{tree} -p revert-develop -m "Revert back to 9d84997"
d4fd0dc397811c5511709b8291045d5d37db65dc
todd@todd-VirtualBox:~/go/src/github.com/tidepool-org/platform$ git merge --ff-only d4fd0dc397811c5511709b8291045d5d37db65dc
Updating 4bdec48d..d4fd0dc3
Fast-forward
 Dockerfile.tools                                                                           |   8 ++---
 data/forecast.go                                                                           |  63 -------------------------------------
 data/forecast_test.go                                                                      |  69 ----------------------------------------
 data/service/service/standard.go                                                           |  14 ---------
 data/storeDEPRECATED/mongo/mongo.go                                                        |  14 ---------
 data/storeDEPRECATED/store.go                                                              |   2 --
 data/storeDEPRECATED/test/data_session.go                                                  |   5 ---
 data/types/blood/glucose/continuous/continuous.go                                          |  17 ++++++++--
 data/types/blood/glucose/continuous/continuous_test.go                                     |  32 ++++++++++++++++++-
 data/types/blood/glucose/continuous/rate.go                                                |  43 -------------------------
 data/types/blood/glucose/continuous/rate_test.go                                           |  71 ------------------------------------------
 data/types/blood/glucose/continuous/trend.go                                               |  45 ---------------------------
 data/types/blood/glucose/continuous/trend_test.go                                          |  18 -----------
 data/types/calculator/calculator.go                                                        |  15 ---------
 data/types/calculator/calculator_test.go                                                   |  10 ------
 data/types/device/{sensor/sensor.go => devicesensor/devicesensor.go}                       |  14 ++++-----
 data/types/device/{sensor/sensor_suite_test.go => devicesensor/devicesensor_suite_test.go} |   2 +-
 data/types/device/{sensor/sensor_test.go => devicesensor/devicesensor_test.go}             |  74 +++++++++++++++++++++----------------------
 data/types/device/factory/factory.go                                                       |   8 -----
 data/types/device/transmitter/transmitter.go                                               |  62 ------------------------------------
 data/types/device/transmitter/transmitter_suite_test.go                                    |  11 -------
 data/types/device/transmitter/transmitter_test.go                                          | 180 ---------------------------------------------------------------------------------------------------------
 data/types/devicestatus/devicestatus.go                                                    |  82 ------------------------------------------------
 data/types/devicestatus/devicestatus_suite_test.go                                         |  11 -------
 data/types/devicestatus/devicestatus_test.go                                               |  78 ----------------------------------------------
 data/types/devicestatus/status/battery.go                                                  |  35 ---------------------
 data/types/devicestatus/status/battery_test.go                                             |  51 ------------------------------
 data/types/devicestatus/status/reservoirremaining.go                                       |  37 ----------------------
 data/types/devicestatus/status/reservoirremaining_test.go                                  |  51 ------------------------------
 data/types/devicestatus/status/signalstrength.go                                           |  37 ----------------------
 data/types/devicestatus/status/signalstrength_test.go                                      |  51 ------------------------------
 data/types/devicestatus/status/status.go                                                   | 116 --------------------------------------------------------------------
 data/types/devicestatus/status/status_suite_test.go                                        |  11 -------
 data/types/devicestatus/status/status_test.go                                              |  64 -------------------------------------
 data/types/factory/factory.go                                                              |   4 ---
 request/values_parser.go                                                                   |  28 -----------------
 service/api/api.go                                                                         |  10 +++---
 structure/parser.go                                                                        |   1 -
 structure/parser/object_parser.go                                                          |  28 -----------------
 task/service/service/service.go                                                            |   4 +--
 tools/tapi/README.md                                                                       |   4 +--
 tools/tapi/cmd/cmd.go                                                                      |   3 +-
 tools/tapi/cmd/common.go                                                                   |   2 +-
 tools/tapi/cmd/user.go                                                                     |  28 -----------------
 44 files changed, 105 insertions(+), 1408 deletions(-)
 delete mode 100644 data/forecast.go
 delete mode 100644 data/forecast_test.go
 delete mode 100644 data/types/blood/glucose/continuous/rate.go
 delete mode 100644 data/types/blood/glucose/continuous/rate_test.go
 delete mode 100644 data/types/blood/glucose/continuous/trend.go
 delete mode 100644 data/types/blood/glucose/continuous/trend_test.go
 rename data/types/device/{sensor/sensor.go => devicesensor/devicesensor.go} (77%)
 rename data/types/device/{sensor/sensor_suite_test.go => devicesensor/devicesensor_suite_test.go} (81%)
 rename data/types/device/{sensor/sensor_test.go => devicesensor/devicesensor_test.go} (72%)
 delete mode 100644 data/types/device/transmitter/transmitter.go
 delete mode 100644 data/types/device/transmitter/transmitter_suite_test.go
 delete mode 100644 data/types/device/transmitter/transmitter_test.go
 delete mode 100644 data/types/devicestatus/devicestatus.go
 delete mode 100644 data/types/devicestatus/devicestatus_suite_test.go
 delete mode 100644 data/types/devicestatus/devicestatus_test.go
 delete mode 100644 data/types/devicestatus/status/battery.go
 delete mode 100644 data/types/devicestatus/status/battery_test.go
 delete mode 100644 data/types/devicestatus/status/reservoirremaining.go
 delete mode 100644 data/types/devicestatus/status/reservoirremaining_test.go
 delete mode 100644 data/types/devicestatus/status/signalstrength.go
 delete mode 100644 data/types/devicestatus/status/signalstrength_test.go
 delete mode 100644 data/types/devicestatus/status/status.go
 delete mode 100644 data/types/devicestatus/status/status_suite_test.go
 delete mode 100644 data/types/devicestatus/status/status_test.go
```

The interesting bit in the log above is the use of `git commit-tree`. This command creates a new detached commit where the file contents of the repo are the same as they were at commit 9d84997, which is the first common commit of `develop` and `master` (i.e. the merge base). The resulting commit d4fd0dc is then merged to the active branch `revert-develop`.

The file changes in this PR are the exact opposite of those in https://github.com/tidepool-org/platform/pull/459.

One thing to note is that this branch also reverts some hotfix changes (https://github.com/tidepool-org/platform/pull/448) which were pushed first to `master` and then cherry-picked in `develop` (thus the different shas in both branches). They should be replayed again (cherry-picked) on top of develop in order to avoid the removal of the hotfix from `master` when this PR makes its way there. I didn't do this in this PR to illustrate that the changes here are the exact opposite of #459.

As discussed during the backend huddle, this revert is required to unblock immediate releases to production. If your work was reverted you can cherry-pick it in a new feature branch. 

Edit: `git revert` didn't work, because the commit range contained merge commits which can't be reverted automatically.

### CODE REVIEW

**Comment by toddkazakov** [comment]
They are in master, but they were cherry picked to develop, which is the reason for the duplication in both branches. You can open a PR that merges master to develop to see what else is missing. I only saw other merge commits which should be OK.

**Comment by toddkazakov** [comment]
I also mention this in the PR description

> One thing to note is that this branch also reverts some hotfix changes (#448) which were pushed first to master and then cherry-picked in develop (thus the different shas in both branches). They should be replayed again (cherry-picked) on top of develop in order to avoid the removal of the hotfix from master when this PR makes its way there. I didn't do this in this PR to illustrate that the changes here are the exact opposite of #459.

**Comment by pazaan** [comment]
@toddkazakov Gah! Sorry, for not reading that through thoroughly 🤦‍♂

**Comment by jamesraby** [comment]
Hmm - this is going to be a bit messy considering that I have two reasonably large branches that are based on this - but I will figure out how to put it all together.

**Comment by toddkazakov** [comment]
Closing this one as we decided we will switch to Github flow

**Pull request closed without merging**
